routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/tasks', 'TaskController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'name',
        'description',
        'date',  
        'priority',  
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$tasks = Task::all();
        $tasks = Task::orderBy('date', 'ASC')->orderBy('priority', 'ASC')->get();


        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required',
            'date'=>'required',
            'priority'=>'required'
        ]);

        $contact = new Task([
            'name' => $request->get('name'),
            'description' => $request->get('description'),
            'date' => $request->get('date'),
            'priority' => $request->get('priority')
        ]);
        $contact->save();
        return redirect('/tasks')->with('success', 'Task saved!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        return view('tasks.edit', compact('task'));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required',
            'date'=>'required',
            'priority'=>'required'
        ]);

        $task = Task::find($id);
        $task->name =  $request->get('name');
        $task->description = $request->get('description');
        $task->date = $request->get('date');
        $task->priority = $request->get('priority');
        $task->save();

        return redirect('/tasks')->with('success', 'Task updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();
        return redirect('/tasks')->with('success', 'Task deleted!');
    }
}

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>ToDo App</title>
	<link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> 

	<!-- Font Awesome -->
	<script src="https://kit.fontawesome.com/98fddee540.js" crossorigin="anonymous"></script>
	<style type="text/css">
		.fa{
			margin-right:8px;
		}
		#priority-1{
			background-color: rgb(242,91,99); /* Red */
			width:10px;
			text-align:center;
		}
		#priority-2{
			background-color: rgb(255,162,100); /* Amber (Yellow/Orange) */
			width:10px;
			text-align:center;
		}
		#priority-3{
			background-color: rgb(114,217,108); /* Green */
			width:10px;
			text-align:center;
		}
	</style>
</head>

<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/tasks/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3 text-center">Add a task</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('tasks.store') }}">
          @csrf
          <div class="form-group">    
              <label for="name">Name:</label>
              <input type="text" class="form-control" name="name"/>
          </div>

          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>

          <div class="form-group">
              <label for="date">Due Date:</label>
              <input type="text" class="form-control" name="date"/>
          </div>

          <div class="form-group">
              <label for="priority">Priority:</label>
              <select class="form-control" name="priority">
                <option value="1">1 (Urgent)</option>
                <option value="2">2 (Average)</option>
                <option value="3">3 (Not Urgent)</option>
              </select>
          </div>

          <button type="submit" class="btn btn-success">
            <span class="fa fa-check" aria-hidden="true"></span>  Add task
          </button>
          <a href="/tasks" class="btn btn-secondary" style="float:right;"><span class="fa fa-arrow-left" aria-hidden="true"></span> Back</a>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/tasks/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3 text-center">Update a task</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('tasks.update', $task->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="first_name"> Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $task->name }}" />
            </div>

            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" name="description" value="{{ $task->description }}" />
            </div>

            <div class="form-group">
                <label for="date">Due Date:</label>
                <input type="text" class="form-control" name="date" value="{{ $task->date }}" />
            </div>

            <div class="form-group">
                <label for="priority">Priority:</label>
                <select class="form-control" name="priority">
                  <option value="{{ $task->priority }}"> {{ $task->priority }} (Current Selection) </option>
                  <option value="1">1 (Urgent)</option>
                  <option value="2">2 (Average)</option>
                  <option value="3">3 (Not Urgent)</option>
                </select>
            </div>
            <button type="submit" class="btn btn-success">
                <span class="fa fa-check" aria-hidden="true"></span> Update
            </button>
          <a href="/tasks" class="btn btn-secondary" style="float:right;"><span class="fa fa-arrow-left" aria-hidden="true"></span> Back</a>
        </form>
    </div>
</div>
@endsection

resources/views/tasks/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
<div class="col-sm-12">
    <h1 class="display-3 text-center">Tasks</h1>
    <div>
        <a style="float:left;margin-bottom: 19px;" href="{{ route('tasks.create')}}" class="btn btn-primary"><span class="fa fa-plus" aria-hidden="true"></span> New Task</a>
        <h5 class="font-weight-bold" style="float:right;margin-bottom: 0;"> {{$tasks->count()}} Tasks</h5>
    </div>
  <table class="table table-hover">
    <thead class="font-weight-bold">
        <tr>
          <td>Priority</td>
          <td>Name</td>
          <td>Description</td>
          <td>Due Date</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($tasks as $task)
        <tr>
            <td id="priority-{{$task->priority}}">{{$task->priority}}</td>
            <td>{{$task->name}}</td>
            <td>{{$task->description}}</td>
            <td>{{$task->date}}</td>
            <td>
                <a href="{{ route('tasks.edit',$task->id)}}" class="btn btn-primary"><span class="fa fa-pencil" aria-hidden="true"></span>Edit</a>
            </td>
            <td>
                <form action="{{ route('tasks.destroy', $task->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit"><span class="fa fa-trash" aria-hidden="true"></span>Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
@endsection